### ISSUE TITLE
Trying to use emitter inside a closure -- any idea why this doesn't work?

### ISSUE THREAD

**Issue by alxpettit** [dmitryvk/async-fn-stream#1]
My use case is a wrapper around `cpal` closure-driven functions to achieve a pure stream approach.

Relevant code is [here](https://github.com/alxpettit/walkie-talkie/blob/trying-to-remove-mpsc/src/mic/mod.rs). Currently, it seems to fail silently when I try to send values this way. Any idea why?

**Comment by dmitryvk** [comment]
Hi!
One issue that I see is that the closure returns early - hence the stream gets EOF'd and is consequently dropped.
If I do this:
```
pub fn getstream_from_mic(
    config: cpal::StreamConfig,
    input_device: cpal::Device,
) -> impl Stream<Item = PCMResult> {
    try_fn_stream(|emitter| async move {
        ...

        input_stream.play()?;

        let never_ready = poll_fn::<(), _>(|_| std::task::Poll::Pending);

        never_ready.await;

        Ok(())
    })
```
then there is some activity - at least the callback is firing.

The other issue is that the stream is producing data in one async runtime (`block_on` is a mini-runtime) and the consumer is in another async runtime. I didn't anticipate that case :)

This is a valid use case - I'll try to come up with something.

**Comment by alxpettit** [comment]
Yay! I'm excited to try it out :)

**Comment by dmitryvk** [comment]
It seems to that implementing something like this would not be a good idea for this library. It would be more expensive performance-wise to allow moving the emitter struct to other thread and to have it behave like a message channel.
I guess it makes more sense to use the async channel in the first place.

This would be an example how to achieve sending values from another thread:
```
let (tx, mut rx) = tokio::sync::mpsc::channel(128);

// spawn a thread to send values into `tx`
// ...

fn_stream(|emitter| async move {
    while let Some(item) = rx.recv().await {
        emitter.emit(item).await;
    }
})
```

**Comment by alxpettit** [comment]
Damn, I was already doing that. It seems to introduce significant overhead tho. :S

Thanks for looking into it, anyway.

**Comment by dmitryvk** [comment]
It seems that the overhead comes from sending every sample via stream. I think that it's better to send vectors with many samples instead of individual samples.
E.g.,
```
        for data in rx {
            //for sample in data {
            //    emitter.emit(sample).await;
            //}
            emitter.emit(data).await;
        }
```

**Comment by alxpettit** [comment]
Yeah, no worries, that occurred to me too. :) Unfortunately, the chunks need to be different sizes at different stages, so I'll need to write some annoying chunk resizing logic that avoids copying any data -- if it's less than the target size, add onto it -- then save the rest for next round -- etc. It's notable that this is kind of a toy case for a very high-performance application, so even the overhead reduction from chunking still wouldn't necessarily be acceptable for that. It does work well enough for my toy audio tests, though.
